### ISSUE TITLE
Download faculty profiles with associated tags in a CSV file

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#28] opened 2018-10-19 00:21 UTC
This might become important if we have to take any administrative action if someone posts discriminatory comments or makes inappropriate tags. It can also help us keep track of which tags are user-generated versus tags we came up with, i.e. "scuba-diving" and "bungee-jumping."

**Comment by razzius** [comment] 2018-12-31 07:37
This won't be an issue since tags will be private by default and `public` can be set to false via the admin. Generally I shy away from having data deletion cascading.

User-created tags aren't able to be publicly shared yet, in any case.

**Comment by razzius** [comment] 2018-12-31 07:39
Feel free to propose an alternative mechanism to track our tags such as bungee-jumping @jjchen20 and as long as it doesn't involve cascading deletion I'll probably support implementing it.

**Comment by razzius** [comment] 2019-01-29 07:48
As far as I can tell this is a duplicate of #30, so I'm closing.

**Closed by razzius** 2019-01-29 07:48 UTC
