### ISSUE TITLE
Upload tutorial video

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#7] opened 2018-10-03 02:37 UTC
I will finish this up and get it to you

**Comment by JonKusner** [comment] 2018-10-03 02:38
Video appears after users verify emails on their first time logging in. It has a "skip" function which routes to the profile generation page.

**Comment by JonKusner** [comment] 2018-10-03 03:04
In addition to a "Skip" function. There should be a link to the video transcript, provided below:

1. Welcome to Weave. This 4 minute tutorial will guide you in how to create a faculty profile.
2. First, begin by entering your name and preferred email.
3. You may complete the “Hospital Affiliations” section by typing an institution’s name, seen here with Cambridge Health Alliance. Or, you may click the dialogue box to view the drop down menu and select an institution. This logic of selection will be seen in many other sections below.
4. For the “Clinical Interests” and “Professional Interests” sections, you may select tags as you would with “Hospital Affiliations.” You may also create your own tags by typing out the tag and pressing the enter key.
5. In the “Parts of Me” section, there are no suggested tags. This is a section in which you may create tags that describe aspects of your identity that you would like to share with students and faculty on Weave. Some examples are provided here. Please feel empowered to share any personally meaningful information in this section.
6. For the “Activities I Enjoy” section, you may select tags or create your own tags. Here, we have created “scuba-diving” and “bungee-jumping,” which were not available in the previous list. For more information on how to create tags, please visit our “Help” page.
7. In this text box, you may share additional information with mentees.
8. On the top left hand side, you may upload an image from your computer or device by clicking “Choose file”. The image can then be cropped and adjusted before saving the image by clicking “Save image”.
9. Be sure to use the “I am available to mentor in the following ways” section to communicate any other opportunities that you are willing to offer mentees.
10. The cadence section allows you to demonstrate, on average, how often you would like to meet with mentees.
11. Click “Preview Profile” to see how your profile will appear on Weave.
12. You may at anytime adjust the “on/off” toggle for your profile. When “on”, the toggle will turn blue and this will allow your profile to be searched by mentees. When “off”, your profile will be hidden from others until you flip the toggle back to the “on” position.
13. When you are satisfied with how your profile looks, you may publish your profile! This is how your profile is saved in our system. If you would like to only save your profile and return to edit at a later time, please turn your “on/off” toggle to the “off” position and publish your profile.
14. To view your profile in the view that is searchable to students, navigate to the homepage and click on “Browse all faculty profiles.” You may scroll to find the snapshot of your profile. If you turn the toggle to “off” and refresh the page, your profile will not be viewable or searchable by students or faculty. When the toggle is “on” and the page is refreshed, your profile will be viewable again.
15. When you are finished, you may log out.
16. Of note, for your security, you will be automatically logged off 1 hour after you initially log into Weave.
17. For additional questions, please visit our “Help” page or contact us at weave@hms.harvard.edu. Thank you.

**Comment by jjchen20** [comment] 2018-10-03 17:46
![image](https://user-images.githubusercontent.com/43801169/46428674-79f42580-c6f9-11e8-9062-fd0bea501bfc.png)
Razzi, can you put the video tutorial in the white space here, after faculty have confirmed log in?

**Comment by razzius** [comment] 2018-10-04 07:36
I put the video - uploaded from my personal Vimeo so it has my name on it. Looks pretty good though. The video is public - need a paid subscription for them, to do anything fancier.

Not sure what to do with the transcript, so I'll keep this open, but remove high priority. FWIW the transcript is the description of the Vimeo video.

**Comment by JonKusner** [comment] 2018-10-04 14:10
This looks really good. I like that the create profile is right under the video. I think the page makes a lot of sense. I also think it is fine to have to video for every log in (rather than just the first) because it doesn't autoplay and can easily be skipped.
I think now we are coming up to a couple of interwoven tasks. #10 is to add the tutorial to the help page. This will make a lot more sense and be more sustainable if we first do #14 which is to transition the help page to HTML.
I don't feel strongly about making a button for the video transcript available when people log in, though I do think this should be available as a static page linked to from the help page (just below the video once it is there)

**Comment by jjchen20** [comment] 2018-10-04 17:02
This looks great!

Three recommendations:
1) Can we move the video slightly up, so people don't have to scroll to see
the "Continue to home" button? "Continue to home" is important because if
you click directly on "HMS Weave," it looks like you haven't logged in yet.
2) I agree with Jon about Issue #10. For faculty who skip the tutorial then
realize they don't know how to make a faculty profile and want to watch the
video, they need a way to get back to the video tutorial without having to
log out and log back in.
3) Once the video is on the Help page, let's include the following sentence
on the initial confirm log-in page: "You may return to this tutorial at any
time by visiting the "Help" page."

**Comment by jjchen20** [comment] 2018-10-05 17:40
Can we actually have two buttons on the login confirmation page?
1) Create profile
2) Continue to home

**Comment by razzius** [comment] 2018-10-06 23:38
I made it so that you are logged in even if you don't click "continue to home" / "edit profile"

**Comment by razzius** [comment] 2018-10-07 00:11
I'm not convinced that we need 2 buttons on the login confirmation page, now that you can use the top-left weave logo immediately and stay logged in. Closing this issue as the original ask has been adequately met, in my opinion. Feel free to create follow-up issues @JonKusner 	@jjchen20

**Closed by razzius** 2018-10-07 00:12 UTC
Labels: enhancement, high priority
