### ISSUE TITLE
Issue with image uploading/ saving on faculty profile creation page

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#33] opened 2018-10-22 04:49 UTC
There seems to be something funny about the image uploading process. One of the faculty was not able to save her image. The "Save Image" button is gone, and there's additional boxes around the photo. 
![image](https://user-images.githubusercontent.com/43801169/47278110-1c762a80-d57b-11e8-997a-2417dbb19805.png)

**Comment by razzius** [comment] 2018-12-02 06:16
Duplicate of #40? That's some strange behavior.

I did get rid of the "save image" button - the image saves when the profile saves, so currently that's expected behavior. I'm willing to revisit this decision.

**Comment by razzius** [comment] 2018-12-02 08:10
Yeah, I'll close the other.

**Comment by razzius** [comment] 2018-12-30 20:16
Haven't seen this one in a while and I've fixed some things on the profile edit page in the meantime and upgraded `react-avatar-editor`.

Closing until it comes up again. If it does come up again, it'd be great to have steps to reproduce the error.

**Closed by razzius** 2018-12-30 20:16 UTC
Labels: bug, high priority
