### ISSUE TITLE
Faculty unable to add photo to profile

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#40] opened 2018-12-01 03:17 UTC

**Comment by razzius** [comment] 2018-12-02 06:03
@jjchen20 	could you put the steps you believe the faculty took? Is there an email or fullstory for this?

**Comment by jjchen20** [comment] 2018-12-02 06:14
From a faculty on 11/16/18 @ 3:15pm: "When I try to upload a photo, it won't upload. Any suggestions? Thanks!"

**Comment by razzius** [comment] 2018-12-02 08:11
Duplicate of #33

**Closed by razzius** 2018-12-02 08:11 UTC
Labels: bug, high priority
